stages:
    - deploy

variables:
    APP_NAME: makerlog-ui

deploy:
    image: node:12
    stage: deploy
    environment:
        name: production
        url: https://getmakerlog.com/
    only:
        - master
    script:
        - npm install
        - npm run build
        - pip install awsebcli --upgrade --user
        - eb deploy $EB_APP_NAME
