stages:
  - deploy

variables:
  APP_NAME: makerlog-ui

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://next.getmakerlog.com/
  only:
    - master
  script:
    - SSH_PRIVATE_KEY="$(base64 --decode "$SSH_PRIVATE_KEY")"
    - git-push ssh://dokku@mattei.dev:22/$APP_NAME