stages:
    - deploy

variables:
    APP_NAME: makerlog-ui

deploy:
    image: node:12
    stage: deploy
    environment:
        name: production
        url: https://getmakerlog.com/
    only:
        - master
    script:
        - apt update
        - apt install -y git build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev
        - git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git ~/aws
        - chmod +x ~/aws/scripts/bundled_installer
        - ~/aws/scripts/bundled_installer
        - npm install
        - npm run build
        - eb deploy $EB_APP_NAME
