stages:
    - deploy

variables:
    APP_NAME: makerlog-ui

deploy:
    image: node:12
    stage: deploy
    environment:
        name: production
        url: https://getmakerlog.com/
    only:
        - master
    script:
        - apt install -y python3-setuptools python3-pip
        - export PATH=$PATH:~/.local/bin/
        - pip3 install --upgrade --user awsebcli==3.10.0
        - npm install
        - npm run build
        - eb init $EB_APP_NAME
        - eb deploy $EB_APP_NAME
