stages:
    - deploy

variables:
    APP_NAME: makerlog-ui

deploy:
    image: node:12
    stage: deploy
    environment:
        name: production
        url: https://getmakerlog.com/
    only:
        - master
    script:
        - apt update
        - apt install -y python3-setuptools python3-pip git python3
        - pip3 install virtualenv
        - git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git ~/aws
        - python3 ~/aws/scripts/ebcli_installer.py
        - npm install
        - npm run build
        - eb init $EB_APP_NAME
        - eb deploy $EB_APP_NAME
