stages:
    - deploy

variables:
    APP_NAME: makerlog-ui

deploy:
    image: node:12
    stage: deploy
    environment:
        name: production
        url: https://getmakerlog.com/
    only:
        - master
    script:
        - npm install
        - npm run build
        - apt update
        - apt install python3-setuptools
        - easy_install3 pip
        - export PATH=$PATH:~/.local/bin/
        - pip install --upgrade --user awsebcli
        - eb deploy $EB_APP_NAME
