stages:
    - deploy

variables:
    APP_NAME: makerlog-ui

deploy:
    image: node:12
    stage: deploy
    environment:
        name: production
        url: https://getmakerlog.com/
    only:
        - master
    variables:
        LC_CTYPE: "en_US.UTF-8"
        LANG: "en_US.UTF-8"
    script:
        - apt update
        - apt install -y python3-setuptools python3-pip git python3
        - pip install awsebcli --upgrade --user
        - npm install
        - npm run build
        - eb init $EB_APP_NAME
        - eb deploy $EB_APP_NAME
