stages:
    - deploy

variables:
    APP_NAME: makerlog-ui

deploy:
    image: node:12
    stage: deploy
    environment:
        name: production
        url: https://getmakerlog.com/
    only:
        - master
    script:
        - apt update
        - apt install -y python3-setuptools python3-pip python3-dev
        - export LC_ALL=en_US.UTF-8
        - export PATH=$PATH:~/.local/bin/
        - pip3 install --upgrade --user awsebcli
        - npm install
        - npm run build
        - eb deploy $EB_APP_NAME
