name: Deploy master
on:
    push:
        branches:
            - master

jobs:
    cypress-run:
        runs-on: ubuntu-16.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  start: yarn start --ignore-engines
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v1

            - name: Build the slug
              run: |
                  curl -sL https://deb.nodesource.com/setup_12.x | sudo apt install -y nodejs
                  npm install
                  npm run build
                  zip -r deploy.zip .

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v10
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: ${{ secrets.EB_APP_NAME }}
                  environment_name: ${{ secrets.EB_APP_NAME }}-prod
                  version_label: ${{github.SHA}}
                  region: ${{ secrets.AWS_DEFAULT_REGION }}
                  use_existing_version_if_available: true
                  deployment_package: deploy.zip
            - uses: act10ns/slack@v1
              with:
                status: ${{ job.status }}
                steps: ${{ toJson(steps) }}
                channel: '#ops'
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              if: always()
